steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/image-app-462407/my-docker-repo/image-app', '.']

images:
  - 'europe-west1-docker.pkg.dev/image-app-462407/my-docker-repo/image-app'
